name: Deploy

jobs:
  build:
    name: Run deployement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build --if-present
      - uses: akhileshns/heroku-deploy@v3.1.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "humanaid-bo"
          heroku_email: "contact.humanaid@gmail.com"